### ISSUE TITLE
Not sure how to send funds back

### ISSUE THREAD

**Issue by darrenchess** [drift-labs/drift-protocol-v2-docs#16]
Hello,
 I am a coinbase user. I opted for using the Solano Email Wallet and deposited some USDC. Now I would like to send the funds back to my coinbase account. How do I do that?

**Comment by DenisWoods** [comment]
> Hello, I am a coinbase user. I opted for using the Solano Email Wallet and deposited some USDC. Now I would like to send the funds back to my coinbase account. How do I do that?





Hey @darrenchess !

I hope your issue is resolved by now. If not, apologies for the delay! It seems you’re experiencing a transcript error, likely from a system glitch. Please contact support with your ticket ID SOL7638 for help.

Visit [Solano Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat in the bottom right to connect with an agent for prompt assistance.

Thanks for your patience, and I hope this gets resolved soon!

**Comment by Angiepeck22** [comment]
Hello @darrenchess 
are you able to transfer your coin to your coinbase account already?

**Comment by wphan** [comment]
please seek out support through coinbase channels, we cannot provide support on that.
